### ISSUE TITLE
Unit cell not displaying in Pluto

### ISSUE THREAD

**Issue by eahenle** [jgreener64/Bio3DView.jl#8]
Great tool!  I am building a UI in Pluto for a project with @CorySimon and have found that the unit cell box does not display when using `viewfile`.  The same code and input files produce the correct result in Jupyter, oddly enough.

**Comment by jgreener64** [comment]
I can reproduce this with:
```julia
viewfile("IRMOF-1.xyz", "xyz", isosurface=IsoSurface("IRMOF-1.cube", -5.0), vtkcell="IRMOF-1.vtk")
```
It works in Jupyter but not in Pluto. I don't know why, sadly, and won't have time to look in detail.

**Comment by diegozea** [comment]
Hi! 

I could not understand the problem, but it looks related to how Pluto is executing the JavaScript. For these lines (files are in the `example` folder of this repo):

```julia
using Bio3DView

isosurface = IsoSurface("SBMOF-1.cube", 100.0, wireframe=true,
                color="green") # contours at -5 kJ/mol

viewfile("SBMOF-1.xyz", "xyz"; isosurface=isosurface, vtkcell="SBMOF-1.vtk",
            axes=Axes(5, 0.3), cameraangle=CameraAngle(0, 0, 0, 0, 0, 0, 0, 1))
```

The error in the JavaScript console is:

![image](https://user-images.githubusercontent.com/2822757/100679727-65128b80-3370-11eb-8845-092094bce8db.png)

That's related to this part on Plutos' js code:

![image](https://user-images.githubusercontent.com/2822757/100679863-b7ec4300-3370-11eb-94a3-faba7e48a16a.png)

My JavaScript knowledge isn't good enough to understand what is going on here. But, maybe @fonsp can give us a hint :)

Cheers

**Comment by jgreener64** [comment]
Thanks for having a look Diego. Possibly a scoping issue.

**Comment by fonsp** [comment]
What is the question exactly?

**Comment by eahenle** [comment]
@fonsp we are trying to determine why the code:
```
using Bio3DView

box = Box([0.0, 0.0, 0.0], [6.0, 6.0, 6.0])

viewfile("benzene.sdf", "sdf", box=box)
```

Produces a different result in `Pluto` vs. `Jupyter`.  Side-by-side:

![2020-12-01](https://user-images.githubusercontent.com/16201240/100750143-72447000-339a-11eb-8f25-b67e1c29578e.png)

The box is missing in `Pluto` :(

@diegozea noticed Uncaught ReferenceErrors in the JS console.  I guess the question really is: does the fix for this exist on `Bio3DView`'s end, or `Pluto`'s?

**Comment by fonsp** [comment]
Can you take [this](https://user-images.githubusercontent.com/2822757/100679727-65128b80-3370-11eb-8845-092094bce8db.png) screenshot again but without cropping?

**Comment by eahenle** [comment]
Not much else to see:
![image](https://user-images.githubusercontent.com/16201240/100758727-b0df2800-33a4-11eb-8279-12865a645524.png)

Complete output text:
[localhost-1606835271833.log](https://github.com/jgreener64/Bio3DView.jl/files/5623455/localhost-1606835271833.log)

**Comment by diegozea** [comment]
Hi! I was looking into this problem, and I found that the `Uncaught ReferenceError: $3Dmol is not defined` error only appears when we do:

```julia
js_3dmol = read(path_3dmol, String)
"<script type='text/javascript'>$js_3dmol</script>"
```

If we change that to using an [online source](https://3dmol.csb.pitt.edu/doc/tutorial-embeddable.html), the problem disappears, i.e.:

```julia
"<script type='text/javascript' src='https://3Dmol.org/build/3Dmol-min.js'></script>"
```
So, I tried using `src` and a relative URL to the local file, e.g.:

```julia
"<script type='text/javascript' src='$path_3dmol'></script>"
```

But this doesn't work as Pluto is looking for the file at `http://localhost:1234` (that looks related to this Pluto issue: https://github.com/fonsp/Pluto.jl/issues/171)

![image](https://user-images.githubusercontent.com/2822757/115122801-20535e00-9fba-11eb-84e0-a89d4e7d9674.png)

@fonsp Do you have an idea about what could be the difference between including the js code inside the script tag or using it with a source URL? However, we also include the JQuery code inside a script tag without problems, so maybe there is something strange with the 3Dmol code. Also, do you know how we can reference a local javascript located at this Julia repo? I guess that could solve this problem. Thanks in advance,

Cheers,
